### ISSUE TITLE
Question for WorkFlow

### ISSUE THREAD

**Issue by afzl-wtu** [abhint/youtube-downloader#2]
Thanks a lot for such a great example of flask and yt-dlp.
I am a Flutter developer. I was thinking to make a downloader app with the help of yt-dlp. The problem is yt-dlp is a python program and you can not run it in flutter. Moreover you can not run its executable file in Android or ios. So someone on internet mentioned that you can create yt-dlp api on your cloud-platform using flask and then you can make get and post requests to that api and get a working downloader for Android, iOS, Windows, Linux and MacOS (Flutter supports all these platforms).
But here comes major problems.
1. If I send a url to yt-dlp api from my app. YT-DLP will start downloading file on my cloud platform and not on my mobile app.
2. I just want that yt-dlp provide my direct download url of video in json response. So that I directly download the video file on my local mobile app instead of cloud.
3. Also I do not know the workflow of yt-dlp. How a video's audio and video track is downloaded. is it same url or different url.
4. How I will convert the downloaded file to mp4.

It would be great if you guide me.

**Comment by abhint** [comment]
First of all sorry for late 
[YoutubeExplodeDart](https://github.com/Hexer10/youtube_explode_dart) this dart package may help you.
